sudo: false
language: node_js
node_js:
- 9.3.0
os:
- osx
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
script:
- npm test
after_success:
- npm run semantic-release
env:
  global:
  - secure: im3vniEtFXLCwRqWRryeLvn0ToOPGu01CtEYLyREFcQ5ZIe6EPAasSwh3byxlW97g33ccu+M07YFCc6Ohup8LkM3SLExn87g/Y4sFOBBLU1WNeFHnslol4jc9WI5ClvP9EICVzZL5NlZA5hyfp6T5CH4nSzNfoQTeskTaayzA45TJGSQSj6qRdBuPMXKPQQtT3HZtu/Afv82n2S5UUQIXGd9dQpqz3e4/PKEnlH9k4xkj3FkXXAMHAVrnZRErmLOhdfCyMki1XAIgbKV46tecrDMFSs6RN2FtSkWagPjkkOEN1pVxQEHmMUoq893XLDRATd054wjmXOFGnv2HUH18CUUdHVGhLPaleBIBeQkIjuLkExv9wz9INTraK7hIKFabSxRRraH2mV3fBhyhMER4GnGxEnc1U3XuG68Jio0sPmrFaeI3PSH20R0fKgBDIlFC5Bvw4e8VSjglPfTMyAGzkgfdlCzHodfQ19mqJpR2CofK1HtS8hUD8K7Uv5fSCaXWZXAwqE52J2ic9en7Dhe8qUSzT8FlVedk9vuAkI0gVqLIK7Mn2U1nx8yQNpUPkqlTgBPCr9v9Eq5RS5pn6LmkyDcXhNJkZDTTxtLh5weoVcONdM6boYHfTIE525mqDO1xJYpmW08LFW2SHbnjohV+ipSg0vqlUeQnebBRV9DoP8=
  - secure: Mz8NlNN5zM+sb5rf4Y6qmVOL7YaB+GHVOhzvEaku6n98XOMG5HAY3jHAvEXXG6rh1UgbS0hXnuPtllkhqqO2qqnVT7VzJqmH8e2FGSFytLW498EHBirZT7OKTvO4kKG2dyvAq4JkeG41yFhbBWKL9ORzthuWrlwPh/u+dYTB9EWINgiXWli0H1OSREw5h+5SFSBY1PY4nc7Kzw0nNeHbZr5rtnshqaJPBX1ILgvAOMi6OMFbErhZLtY74/3IiSK7gkc9SLu4ksWKtT/JqAniS5dIl+o/POD+dZ6njpKFta/b4YIXYx1UTCg8qs1wa5hY4JSCcOO/pZR1JMMyYvqhY6oms7YBWkPiVnBfORjXpT8+d5Bp+3tmXVwB2Eyq3hVbcyeKR9XuSR+58t3S7LjpZ9R1ehi1Ih2+6tycCKy9t/NQRyvlyOjgihoVTDEQZ5TrKnCvEgTkiGdY937tzuvkHiBKPdmnqdNwJmbXa2pKHNIbh2BwJl6T4lLMT0XxJdpu97ULayDaKouln9BGUeCcjnsfgu9ih+Ji+KPFwvVcTw6X4LN3ZmqfPCQnBLEd+iKE/LWUPTPU4hwqtOd2VjzndRJM6QSGfYrkNKm/ARslZqRALf8e3fMY0aVOHorF/q+yuQbjXiXSGn8nBRCfcSRYAZ8hgTftFDLLgglcjlkJuKE=
